### ISSUE TITLE
Derive macro error

### ISSUE THREAD

**Issue by bsodmike** [Keats/validator#184]
Hi, I'm getting this strange error regarding the derive macro:

```rust
26 | #[derive(Debug, Validate, Deserialize, Serialize)]
   |                 ^^^^^^^^ expected enum `std::option::Option`, found struct `std::string::String`
   |
   = note: expected reference `&std::option::Option<_>`
              found reference `&std::string::String`
   = note: this error originates in the derive macro `Validate` (in Nightly builds, run with -Z macro-backtrace for more info)
```

This is the app config:

```toml
[package]
name = "myapp"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
axum = { version = "0.4", features = ["headers"] }
axum-extra = "0.1.1"
redis = { version = "0.21", features = ["aio", "tokio-comp"] }
sqlx = { version = "0.5", features = [ "runtime-tokio-native-tls" , "postgres",
"uuid", "chrono", "bigdecimal"] }
tracing = "0.1"
tracing-subscriber = { version="0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.9.0"
config = "0.11.0"
glob = "0.3.0"
tower = { version = "0.4.11", features = ["limit", "filter", "util"] }
tower-http = { version = "0.2.0", features = ["trace"] }
hyper = { version = "0.14", features = ["full"] }
rand = "0.8.4"
base64 = "0.13.0"
futures = "0.3.19"
serde_urlencoded = "0.7.0"
regex = "1.5"
chrono = "0.4.19"
validator = { version = "0.14", features = ["derive", "phone", "unic"] }

[dependencies.uuid]
version = "1.0.0-alpha.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde"
]

[dev-dependencies]
taplo = "0.7.0"
```

Using latest stable version of Rust `rustc 1.58.1 (db9d1b20b 2022-01-20)`.
