### ISSUE TITLE
include cargo install instruction in readme

### ISSUE THREAD

**Issue by decapo01** [Keats/validator#89]
Every time I come back to this library I have a bit of trouble figuring out what to add to my cargo.toml file to use this.

It would be nice if the top of the read me said

Installation
-------------

```toml
[dependencies]
validator = "0.10"
validator_derive = "0.10"
```

or where `0.10` could be replaced with whatever the latest version is.
