### ISSUE TITLE
Question: why I can't find .validate() function

### ISSUE THREAD

**Issue by huming2207** [Keats/validator#95]
Hi there,

I'm a Rust beginner started a few days ago. I'm trying to design a server-side Kanban app (like Trello etc) with Actix-web and MongoDB. I'm trying to use your validator library to validate the user registration form. However, my IDE tells me it can't find the `validate()` function. Did I forget to add something?

Here's my project repo: [https://github.com/huming2207/shachiku-rs](https://github.com/huming2207/shachiku-rs)

And here's my environment:

- Host OS: Linux (Manjaro stable)
- Rust 1.41.1
- IDE: Intellij IDEA or CLion + Intellij Rust
- validator: 0.10.0

Here's my struct, in `src/controller/auth.rs`:

![image](https://user-images.githubusercontent.com/4463497/76029612-f04d2500-5f88-11ea-9284-18ada72cde41.png)

As you can see in `src/service/auth.rs`, `seralize` and `deserialize` works:

![image](https://user-images.githubusercontent.com/4463497/76029564-d3185680-5f88-11ea-9c25-de4ecceedbf1.png)

However, there's no such option for `validate`:

![image](https://user-images.githubusercontent.com/4463497/76029808-49b55400-5f89-11ea-874e-9de7c4f382f9.png)

Could you please give me some ideas? Thanks in advance!

Regards,
Jackson

**Comment by Keats** [comment]
I'm not sure why Intellij is not showing it but it comes from the Validate trait that you imported. Not too sure what to do

**Comment by huming2207** [comment]
@Keats Thanks for your reply. Looks like VSCode + Rust-analyzer (or just the official Rust plugin) it has the same issue:

![image](https://user-images.githubusercontent.com/4463497/76127276-5f904b00-6055-11ea-81f7-f7240e75fa5d.png)

And of course, I've added the dependencies in Cargo.toml:

```toml
[dependencies]
mongodb = "0.9"
bson = "0.14.0"
dotenv = "0.15.0"
actix-web = "2"
actix-rt = "1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
web_ical = "0.1.0"
jsonwebtoken = "7.1.0"
log = "0.4.8"
bcrypt = "0.6.1"
validator = "0.10"
validator_derive = "0.10"
```

And `extern crate` well:

![image](https://user-images.githubusercontent.com/4463497/76127143-0cb69380-6055-11ea-9138-26e47a933e92.png)

Are you sure that I've done the right things for importing/adding dependencies?
